[package]
name = "expose-rs"
version = "0.1.3"
edition = "2021"
authors = ["David Agaev"]
repository = "https://github.com/awaydev/expose-rs"
readme = "README.md"
description = "Just exposes your port to public"
categories = ["network-programming"]
keywords = ["upnp", "networking"]
license = "MIT"